import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const supabase = () =>
  createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

// ── Execute handlers per action_type ──────────────────────────
type Handler = (sb: ReturnType<typeof supabase>, payload: any) => Promise<any>;

const HANDLERS: Record<string, Handler> = {
  // MANAGER: maintenance triage
  async maintenance_triage(sb, payload) {
    const { ticket_id, proposed_priority, vendor_name, vendor_id, tenant_notice, tenant_name, property_address } = payload;

    // Update the maintenance request
    if (ticket_id) {
      await sb.from("maintenance_requests").update({
        priority: proposed_priority || "medium",
        vendor_name: vendor_name || null,
        vendor_id: vendor_id || null,
        status: "in_progress",
      }).eq("id", ticket_id);
    }

    // Save tenant notice as a document
    await sb.from("documents").insert({
      name: `Maintenance Notice — ${tenant_name || "Tenant"}`,
      document_type: "other",
      ai_summary: tenant_notice || "Maintenance work has been scheduled for your unit.",
    });

    return { updated_ticket: ticket_id, vendor_assigned: vendor_name, notice_saved: true };
  },

  // INVESTOR: deal memo
  async deal_memo(sb, payload) {
    const { deal_id, address, asking_price, cap_rate, recommendation } = payload;

    // Save memo as a document
    const { data: doc } = await sb.from("documents").insert({
      name: `Deal Memo — ${address}`,
      document_type: "other",
      ai_summary: `IC Deal Memo for ${address}. Asking: $${Number(asking_price).toLocaleString()}. Cap Rate: ${cap_rate}%. Recommendation: ${recommendation}. Generated by CASA Swarm.`,
    }).select().single();

    return { document_id: doc?.id, address, memo_generated: true };
  },

  // DEVELOPER: variance alert / change order
  async variance_alert(sb, payload) {
    const { line_item_id, project_name, line_item_name, budgeted, actual, variance, reforecast_summary } = payload;

    // Flag the line item as at_risk or over
    if (line_item_id) {
      const newStatus = Number(variance) < -10000 ? "over" : "at_risk";
      await sb.from("budget_line_items").update({
        status: newStatus,
        notes: `[SWARM ALERT] ${reforecast_summary}`,
      }).eq("id", line_item_id);
    }

    // Save change-order alert as document
    await sb.from("documents").insert({
      name: `Change Order Alert — ${project_name}: ${line_item_name}`,
      document_type: "other",
      ai_summary: `Variance of $${Number(variance).toLocaleString()} detected. Budget: $${Number(budgeted).toLocaleString()}, Actual: $${Number(actual).toLocaleString()}. ${reforecast_summary}`,
    });

    return { line_item_flagged: line_item_id, alert_saved: true };
  },

  // LAND: offer memo
  async offer_memo(sb, payload) {
    const { parcel_id, address, motivation_score, opportunity_score, distress_score, zoning_code, suggested_offer_low, suggested_offer_high, rationale } = payload;

    // Update parcel status
    if (parcel_id) {
      await sb.from("land_parcels").update({ status: "offer_drafted" }).eq("id", parcel_id);
    }

    // Save offer memo as document
    const { data: doc } = await sb.from("documents").insert({
      name: `Offer Memo — ${address}`,
      document_type: "other",
      ai_summary: `Scores: Motivation ${motivation_score}/10, Opportunity ${opportunity_score}/10, Distress ${distress_score}/10. Zoning: ${zoning_code}. Suggested range: $${Number(suggested_offer_low).toLocaleString()}–$${Number(suggested_offer_high).toLocaleString()}. ${rationale}`,
    }).select().single();

    return { document_id: doc?.id, parcel_status: "offer_drafted", memo_saved: true };
  },

  // BROKER: lease intelligence
  async lease_intelligence(sb, payload) {
    const { listing_id, address, clauses, flagged_risks } = payload;

    // Save lease analysis as document
    const { data: doc } = await sb.from("documents").insert({
      name: `Lease Intelligence — ${address}`,
      document_type: "lease",
      ai_summary: `Clauses: Term=${clauses?.term}, Escalations=${clauses?.escalations}, CAM=${clauses?.cam}, Termination=${clauses?.termination}. Flagged risks: ${(flagged_risks || []).join(", ")}`,
    }).select().single();

    return { document_id: doc?.id, clauses_extracted: true, risks_flagged: flagged_risks?.length || 0 };
  },

  // LENDER: breach package
  async breach_package(sb, payload) {
    const { loan_id, borrower_name, property_address, dscr_current, ltv_current, breach_notice, workout_options } = payload;

    // Save breach notice
    await sb.from("documents").insert({
      name: `Breach Notice — ${property_address}`,
      document_type: "other",
      ai_summary: breach_notice || `Covenant breach: DSCR ${dscr_current} (below 1.0 threshold). LTV ${ltv_current}%.`,
    });

    // Save workout memo
    const { data: doc } = await sb.from("documents").insert({
      name: `Workout Options — ${property_address}`,
      document_type: "other",
      ai_summary: `Borrower: ${borrower_name}. Options: ${(workout_options || []).join("; ")}`,
    }).select().single();

    return { breach_notice_saved: true, workout_memo_id: doc?.id, borrower: borrower_name };
  },
};

export async function POST(req: Request) {
  try {
    const { id } = await req.json();
    if (!id) return NextResponse.json({ error: "Missing id" }, { status: 400 });

    const sb = supabase();

    // Get the action
    const { data: action, error: fetchErr } = await sb
      .from("agent_actions")
      .select("*")
      .eq("id", id)
      .single();

    if (fetchErr || !action) {
      return NextResponse.json({ error: "Action not found" }, { status: 404 });
    }

    if (action.status !== "approved") {
      return NextResponse.json({ error: "Action must be approved before executing" }, { status: 400 });
    }

    // Mark as executing
    await sb.from("agent_actions").update({ status: "executing" }).eq("id", id);

    const handler = HANDLERS[action.action_type];
    if (!handler) {
      await sb.from("agent_actions").update({
        status: "failed",
        error: `No handler for action_type: ${action.action_type}`,
        completed_at: new Date().toISOString(),
      }).eq("id", id);
      return NextResponse.json({ error: "Unknown action_type" }, { status: 400 });
    }

    try {
      const result = await handler(sb, action.payload);

      await sb.from("agent_actions").update({
        status: "completed",
        result,
        completed_at: new Date().toISOString(),
      }).eq("id", id);

      return NextResponse.json({ status: "completed", result });
    } catch (execErr: any) {
      await sb.from("agent_actions").update({
        status: "failed",
        error: execErr.message,
        completed_at: new Date().toISOString(),
      }).eq("id", id);
      return NextResponse.json({ error: execErr.message }, { status: 500 });
    }
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
