import { createServerClient } from "@/lib/supabase-server";
import {
  Card,
  KpiCard,
  PageTitle,
  SectionLabel,
  StaggerIn,
  YellowBadge,
  T,
} from "@/components/ui/primitives";
import { MapPin, Calendar, Ruler, Clock, Navigation } from "lucide-react";

export const dynamic = "force-dynamic";

const fmtMoney = (n: number | null) => {
  if (!n) return "—";
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
};

const fmtDate = (iso: string | null) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
};

export default async function CompsPage() {
  const supabase = createServerClient();

  const { data: comps } = await supabase
    .from("comparable_sales")
    .select("*")
    .order("sale_date", { ascending: false });

  const compList = (comps ?? []) as any[];

  // KPIs
  const totalComps = compList.length;
  const avgPsf =
    compList.length > 0
      ? compList.reduce((s, c) => s + Number(c.price_per_sqft || 0), 0) /
        compList.filter((c) => c.price_per_sqft).length || 0
      : 0;
  const avgDom =
    compList.length > 0
      ? Math.round(
          compList.reduce((s, c) => s + Number(c.days_on_market || 0), 0) /
            compList.filter((c) => c.days_on_market).length || 0
        )
      : 0;
  const distinctSources = new Set(
    compList.map((c) => c.source).filter(Boolean)
  ).size;

  // Group by subject_address
  const grouped = new Map<string, any[]>();
  for (const comp of compList) {
    const subject = comp.subject_address || "Unknown Subject";
    if (!grouped.has(subject)) grouped.set(subject, []);
    grouped.get(subject)!.push(comp);
  }

  return (
    <div className="space-y-10">
      <PageTitle eyebrow="COMPARABLE SALES" title="Market Comps" />

      {/* KPI row */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <KpiCard label="Total Comps" value={totalComps} />
        <KpiCard
          label="Avg $/SF"
          value={avgPsf ? `$${Math.round(avgPsf)}` : "—"}
        />
        <KpiCard label="Avg DOM" value={avgDom ? `${avgDom} days` : "—"} />
        <KpiCard label="Sources" value={distinctSources} />
      </div>

      {/* Empty state */}
      {compList.length === 0 && (
        <Card>
          <div className="py-12 text-center">
            <MapPin
              className="mx-auto mb-4 text-stone-300"
              size={40}
              strokeWidth={1.2}
            />
            <p className="text-lg font-medium text-stone-700">
              No comparable sales yet
            </p>
            <p className="mt-2 text-sm text-stone-500">
              Comparable sales will appear here once they are imported or
              generated by an analysis run.
            </p>
          </div>
        </Card>
      )}

      {/* Grouped by subject */}
      {Array.from(grouped.entries()).map(([subject, subjectComps], gi) => {
        const avgSubjectPsf =
          subjectComps.filter((c) => c.price_per_sqft).length > 0
            ? subjectComps
                .filter((c) => c.price_per_sqft)
                .reduce((s, c) => s + Number(c.price_per_sqft), 0) /
              subjectComps.filter((c) => c.price_per_sqft).length
            : null;
        const avgSubjectPrice =
          subjectComps.filter((c) => c.sale_price).length > 0
            ? subjectComps
                .filter((c) => c.sale_price)
                .reduce((s, c) => s + Number(c.sale_price), 0) /
              subjectComps.filter((c) => c.sale_price).length
            : null;

        return (
          <StaggerIn key={subject} index={gi}>
            <div className="space-y-4">
              {/* Subject header */}
              <div className="flex items-end justify-between">
                <div>
                  <SectionLabel>SUBJECT PROPERTY</SectionLabel>
                  <h2 className="mt-1 text-xl font-medium tracking-tight text-stone-900">
                    {subject}
                  </h2>
                </div>
                <div className="hidden gap-6 text-right sm:flex">
                  {avgSubjectPrice && (
                    <div>
                      <p className="text-[10px] uppercase tracking-widest text-stone-500">
                        Avg Sale Price
                      </p>
                      <p className="text-lg font-medium text-stone-900">
                        {fmtMoney(avgSubjectPrice)}
                      </p>
                    </div>
                  )}
                  {avgSubjectPsf && (
                    <div>
                      <p className="text-[10px] uppercase tracking-widest text-stone-500">
                        Avg $/SF
                      </p>
                      <p className="text-lg font-medium text-stone-900">
                        ${Math.round(avgSubjectPsf)}
                      </p>
                    </div>
                  )}
                  <div>
                    <p className="text-[10px] uppercase tracking-widest text-stone-500">
                      Comps
                    </p>
                    <p className="text-lg font-medium text-stone-900">
                      {subjectComps.length}
                    </p>
                  </div>
                </div>
              </div>

              {/* Comp cards grid */}
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {subjectComps.map((comp, ci) => (
                  <StaggerIn key={comp.id ?? ci} index={ci}>
                    <Card>
                      <div className="space-y-3">
                        {/* Address */}
                        <div>
                          <p className="font-medium text-stone-900">
                            {comp.comp_address || "—"}
                          </p>
                          <p className="text-sm text-stone-500">
                            {[comp.comp_city, comp.comp_state, comp.comp_zip]
                              .filter(Boolean)
                              .join(", ")}
                          </p>
                        </div>

                        {/* Price row */}
                        <div className="flex items-baseline justify-between">
                          <span className="text-2xl font-semibold tracking-tight text-stone-900">
                            {fmtMoney(comp.sale_price)}
                          </span>
                          {comp.price_per_sqft && (
                            <span className="text-sm font-medium text-stone-600">
                              ${Number(comp.price_per_sqft).toFixed(0)}/sf
                            </span>
                          )}
                        </div>

                        {/* Detail grid */}
                        <div className="grid grid-cols-3 gap-2 rounded-2xl bg-[#FAFAF7] p-3">
                          <div className="text-center">
                            <p className="text-[10px] uppercase tracking-widest text-stone-400">
                              Beds
                            </p>
                            <p className="text-sm font-medium text-stone-800">
                              {comp.beds ?? "—"}
                            </p>
                          </div>
                          <div className="text-center">
                            <p className="text-[10px] uppercase tracking-widest text-stone-400">
                              Baths
                            </p>
                            <p className="text-sm font-medium text-stone-800">
                              {comp.baths ?? "—"}
                            </p>
                          </div>
                          <div className="text-center">
                            <p className="text-[10px] uppercase tracking-widest text-stone-400">
                              Sqft
                            </p>
                            <p className="text-sm font-medium text-stone-800">
                              {comp.sqft
                                ? Number(comp.sqft).toLocaleString()
                                : "—"}
                            </p>
                          </div>
                        </div>

                        {/* Meta row */}
                        <div className="flex flex-wrap items-center gap-3 text-xs text-stone-500">
                          <span className="inline-flex items-center gap-1">
                            <Calendar size={12} />
                            {fmtDate(comp.sale_date)}
                          </span>
                          {comp.days_on_market != null && (
                            <span className="inline-flex items-center gap-1">
                              <Clock size={12} />
                              {comp.days_on_market} DOM
                            </span>
                          )}
                          {comp.distance_miles != null && (
                            <span className="inline-flex items-center gap-1">
                              <Navigation size={12} />
                              {Number(comp.distance_miles).toFixed(1)} mi
                            </span>
                          )}
                          {comp.year_built && (
                            <span>Built {comp.year_built}</span>
                          )}
                        </div>

                        {/* Source badge */}
                        {comp.source && <YellowBadge>{comp.source}</YellowBadge>}

                        {/* Adjusted price */}
                        {comp.adjusted_price && (
                          <div className="rounded-xl border border-stone-200 bg-[#FAFAF7] p-3">
                            <p className="text-[10px] uppercase tracking-widest text-stone-400">
                              Adjusted Price
                            </p>
                            <p className="text-base font-semibold text-stone-900">
                              {fmtMoney(comp.adjusted_price)}
                            </p>
                            {comp.adjustment_notes && (
                              <p className="mt-1 text-xs text-stone-500">
                                {comp.adjustment_notes}
                              </p>
                            )}
                          </div>
                        )}
                      </div>
                    </Card>
                  </StaggerIn>
                ))}
              </div>
            </div>
          </StaggerIn>
        );
      })}
    </div>
  );
}
